version: '2'

networks:
  default:

services:

  elasticsearch:
    image: ind3x/rpi-elasticsearch:latest
    restart: unless-stopped
    volumes:
      - /media/Main_/data/elasticsearch/data:/usr/share/elasticsearch/data 
    ports:
      - "9200:9200" 
      - "9300:9300"
    

  logstash:
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    restart: unless-stopped
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - /var/log:/var/log
    ports:
      - "5000:5000"
    links:
      - elasticsearch
