version: '2'

networks:
  default:

services:

  elasticsearch:
    image: ind3x/rpi-elasticsearch:latest
    restart: unless-stopped
    volumes:
      - /media/Main_/data/elasticsearch/data:/usr/share/elasticsearch/data 
    ports:
      - "9200:9200" 
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
    mem_limit: 365m
    

  logstash:
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    restart: unless-stopped
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - /var/log:/var/log
    ports:
      - "5000:5000/udp"
      - "5001:5001/udp"
    depends_on:
      - elasticsearch
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    mem_limit: 365m

  influxdb:
    image: hypriot/rpi-influxdb
    ports: 
      - "8086:8086"
    volumes:
      - /etc/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - /media/Main/data/influxdb/meta:/media/Main/data/influxdb/meta
      - /media/Main/data/influxdb/data:/media/Main/data/influxdb/data
      - /media/Main/data/influxdb/wal:/media/Main/data/influxdb/wal

  telegraf:
    image: arm32v7/telegraf:latest
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - /etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
