version: '2'

networks:
  default:

services:
  grafana:
    image: logging/grafana
    build grafana/
    restart: unless-stopped
    networks:
      - default
    ports:
      - 3000:3000
    volumes:
      - /mnt/data/grafana:/var/lib/grafana
    env_file:
      - config.monitoring

  kibana:
    image: logging/kibana
    build: kibana/
    restart: unless-stopped
    ports:
      - "5601:5601"

  elasticsearch:
    image: ind3x/rpi-elasticsearch:latest
    restart: unless-stopped
    volumes:
      - /mnt/data/elasticsearch/data:/usr/share/elasticsearch/data 
    ports:
      - "9200:9200" 
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
    mem_limit: 256m
    
  logstash:
    image: logging/logstash
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    restart: unless-stopped
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - /var/log:/var/log
    ports:
      - "5000:5000/udp"
      - "5001:5001/udp"
    depends_on:
      - elasticsearch
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    mem_limit: 256m

  influxdb:
    build: influxdb
    image: logging/influxdb
    command: influxd -config=/etc/influxdb/influxdb.conf
    restart: unless-stopped
    ports: 
      - "8086:8086"
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - /mnt/data/influxdb:/media/Main/data/influxdb
    mem_limit: 256m

  telegraf:
    build: telegraf
    image: logging/telegraf
    restart: unless-stopped
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    mem_limit: 256m
